/*
    GLTF converted to JSX by  https://github.com/pmndrs/gltfjsx
*/
import { Float, useGLTF } from "@react-three/drei";
import { MODELS } from "../utils/constants";

/*
  Required Modifications
  - Suzzane: 
    <Float floatingRange={[-0.05, 0.05]} rotationIntensity={0.3}>
    onPointerDown={onPointerHandlers.onSuzanne}
 */

export function BrokenDownCity({
  onPointerHandlers = {},
}: {
  onPointerHandlers?: { [x: string]: (e: any) => void };
}) {
  const { nodes, materials } = useGLTF(MODELS.CITY) as any;

  return (
    <group name="Scene">
      <group name="tech-center" userData={{ name: "tech-center" }}>
        <mesh
          name="tech-center_1"
          castShadow
          receiveShadow
          geometry={nodes["tech-center_1"].geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="tech-center_2"
          castShadow
          receiveShadow
          geometry={nodes["tech-center_2"].geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="tech-center_3"
          castShadow
          receiveShadow
          geometry={nodes["tech-center_3"].geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="tech-center_4"
          castShadow
          receiveShadow
          geometry={nodes["tech-center_4"].geometry}
          material={materials["general-roof"]}
        />
        <mesh
          name="tech-center_5"
          castShadow
          receiveShadow
          geometry={nodes["tech-center_5"].geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="tech-center_6"
          castShadow
          receiveShadow
          geometry={nodes["tech-center_6"].geometry}
          material={materials["window-clear"]}
        />
      </group>
      <group
        name="grocery-store-outer"
        userData={{ name: "grocery-store-outer" }}
      >
        <mesh
          name="Mesh_large_buildingF"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingF.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_large_buildingF_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingF_1.geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="Mesh_large_buildingF_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingF_2.geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="Mesh_large_buildingF_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingF_3.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_large_buildingF_4"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingF_4.geometry}
          material={materials["general-roof"]}
        />
        <mesh
          name="Mesh_large_buildingF_5"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingF_5.geometry}
          material={materials["window-clear"]}
        />
      </group>
      <mesh
        name="grocery-store-inner"
        castShadow
        receiveShadow
        geometry={nodes["grocery-store-inner"].geometry}
        material={nodes["grocery-store-inner"].material}
        userData={{ name: "grocery-store-inner" }}
      />
      <Float floatingRange={[-0.05, 0.05]} rotationIntensity={0.3}>
        <mesh
          onPointerDown={onPointerHandlers.onSuzanne}
          name="Suzanne"
          castShadow
          receiveShadow
          geometry={nodes.Suzanne.geometry}
          material={nodes.Suzanne.material}
          userData={{ name: "Suzanne" }}
        />
      </Float>
      <group name="long-background" userData={{ name: "long-background" }}>
        <mesh
          name="Mesh_large_buildingG"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingG.geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="Mesh_large_buildingG_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingG_1.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_large_buildingG_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingG_2.geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="Mesh_large_buildingG_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingG_3.geometry}
          material={materials["general-borders"]}
        />
      </group>
      <group name="tall-corner" userData={{ name: "tall-corner" }}>
        <mesh
          name="Mesh_skyscraperE"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperE.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_skyscraperE_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperE_1.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_skyscraperE_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperE_2.geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="Mesh_skyscraperE_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperE_3.geometry}
          material={materials["general-roof"]}
        />
        <mesh
          name="Mesh_skyscraperE_4"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperE_4.geometry}
          material={materials["secondary-wall"]}
        />
      </group>
      <group name="skyscraper-small" userData={{ name: "skyscraper-small" }}>
        <mesh
          name="Mesh_skyscraperA"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperA.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_skyscraperA_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperA_1.geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="Mesh_skyscraperA_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperA_2.geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="Mesh_skyscraperA_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperA_3.geometry}
          material={materials["general-window"]}
        />
      </group>
      <group name="skyscraper-tall" userData={{ name: "skyscraper-tall" }}>
        <mesh
          name="Mesh_skyscraperC"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperC.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_skyscraperC_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperC_1.geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="Mesh_skyscraperC_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperC_2.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_skyscraperC_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperC_3.geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="Mesh_skyscraperC_4"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_skyscraperC_4.geometry}
          material={materials["general-roof"]}
        />
      </group>
      <group name="small_buildingA" userData={{ name: "small_buildingA" }}>
        <mesh
          name="Mesh_small_buildingA"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingA.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_small_buildingA_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingA_1.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_small_buildingA_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingA_2.geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="Mesh_small_buildingA_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingA_3.geometry}
          material={materials["general-wall"]}
        />
      </group>
      <group name="small_buildingB" userData={{ name: "small_buildingB" }}>
        <mesh
          name="Mesh_small_buildingC001"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingC001.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_small_buildingC001_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingC001_1.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_small_buildingC001_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingC001_2.geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="Mesh_small_buildingC001_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingC001_3.geometry}
          material={materials["secondary-wall"]}
        />
      </group>
      <mesh
        name="small_buildingB-inner"
        castShadow
        receiveShadow
        geometry={nodes["small_buildingB-inner"].geometry}
        material={nodes["small_buildingB-inner"].material}
        userData={{ name: "small_buildingB-inner" }}
      />
      <group
        name="stairs"
        position={[46.63, 0.12, 22.73]}
        scale={[4.68, 4.83, 7.38]}
        userData={{ name: "stairs" }}
      >
        <mesh
          name="small_buildingB-inner-stair"
          castShadow
          receiveShadow
          geometry={nodes["small_buildingB-inner-stair"].geometry}
          material={materials.wood}
        />
        <mesh
          name="small_buildingB-inner-stair_1"
          castShadow
          receiveShadow
          geometry={nodes["small_buildingB-inner-stair_1"].geometry}
          material={materials.woodDark}
        />
      </group>
      <group name="big-building" userData={{ name: "big-building" }}>
        <mesh
          name="Mesh_large_buildingA"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingA.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_large_buildingA_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingA_1.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_large_buildingA_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingA_2.geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="Mesh_large_buildingA_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_large_buildingA_3.geometry}
          material={materials["general-wall"]}
        />
      </group>
      <group name="post-office" userData={{ name: "post-office" }}>
        <mesh
          name="Mesh_small_buildingE"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingE.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_small_buildingE_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingE_1.geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="Mesh_small_buildingE_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingE_2.geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="Mesh_small_buildingE_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingE_3.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_small_buildingE_4"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingE_4.geometry}
          material={materials["general-roof"]}
        />
      </group>
      <mesh
        name="post-office-inner"
        castShadow
        receiveShadow
        geometry={nodes["post-office-inner"].geometry}
        material={nodes["post-office-inner"].material}
        userData={{ name: "post-office-inner" }}
      />
      <group
        name="MAIL"
        position={[4.556, 0.656, 1.231]}
        rotation={[Math.PI / 2, 0, 0]}
        userData={{ name: "MAIL" }}
      >
        <mesh
          name="Mailbox"
          castShadow
          receiveShadow
          geometry={nodes.Mailbox.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          name="Mailbox_1"
          castShadow
          receiveShadow
          geometry={nodes.Mailbox_1.geometry}
          material={materials.MailBoxBlue}
        />
        <mesh
          name="Mailbox_2"
          castShadow
          receiveShadow
          geometry={nodes.Mailbox_2.geometry}
          material={materials["Material.002"]}
        />
      </group>
      <group
        name="middle-building"
        position={[-0.89, 0, 0]}
        userData={{ name: "middle-building" }}
      >
        <mesh
          name="middle-building_1"
          castShadow
          receiveShadow
          geometry={nodes["middle-building_1"].geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="middle-building_2"
          castShadow
          receiveShadow
          geometry={nodes["middle-building_2"].geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="middle-building_3"
          castShadow
          receiveShadow
          geometry={nodes["middle-building_3"].geometry}
          material={materials["general-roof"]}
        />
        <mesh
          name="middle-building_4"
          castShadow
          receiveShadow
          geometry={nodes["middle-building_4"].geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="middle-building_5"
          castShadow
          receiveShadow
          geometry={nodes["middle-building_5"].geometry}
          material={materials["secondary-wall"]}
        />
      </group>
      <group name="restaurant" userData={{ name: "restaurant" }}>
        <mesh
          name="Mesh_small_buildingD"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingD.geometry}
          material={materials["general-borders"]}
        />
        <mesh
          name="Mesh_small_buildingD_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingD_1.geometry}
          material={materials["general-wall"]}
        />
        <mesh
          name="Mesh_small_buildingD_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingD_2.geometry}
          material={materials["secondary-wall"]}
        />
        <mesh
          name="Mesh_small_buildingD_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingD_3.geometry}
          material={materials["general-window"]}
        />
        <mesh
          name="Mesh_small_buildingD_4"
          castShadow
          receiveShadow
          geometry={nodes.Mesh_small_buildingD_4.geometry}
          material={materials["general-roof"]}
        />
      </group>
      <group name="space-bar" userData={{ name: "space-bar" }}>
        <mesh
          name="mesh325673256"
          castShadow
          receiveShadow
          geometry={nodes.mesh325673256.geometry}
          material={materials.mat17}
        />
        <mesh
          name="mesh325673256_1"
          castShadow
          receiveShadow
          geometry={nodes.mesh325673256_1.geometry}
          material={materials.mat16}
        />
        <mesh
          name="mesh325673256_2"
          castShadow
          receiveShadow
          geometry={nodes.mesh325673256_2.geometry}
          material={materials.mat22}
        />
        <mesh
          name="mesh325673256_3"
          castShadow
          receiveShadow
          geometry={nodes.mesh325673256_3.geometry}
          material={materials.mat25}
        />
        <mesh
          name="mesh325673256_4"
          castShadow
          receiveShadow
          geometry={nodes.mesh325673256_4.geometry}
          material={materials.mat15}
        />
        <mesh
          name="mesh325673256_5"
          castShadow
          receiveShadow
          geometry={nodes.mesh325673256_5.geometry}
          material={materials.mat24}
        />
      </group>
      <mesh
        name="grass"
        castShadow
        receiveShadow
        geometry={nodes.grass.geometry}
        material={materials.grass}
        userData={{ name: "grass" }}
      />
      <group
        name="park-wall"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        userData={{ name: "park-wall" }}
      >
        <mesh
          name="Wall_SecondAge"
          castShadow
          receiveShadow
          geometry={nodes.Wall_SecondAge.geometry}
          material={materials.Stone}
        />
        <mesh
          name="Wall_SecondAge_1"
          castShadow
          receiveShadow
          geometry={nodes.Wall_SecondAge_1.geometry}
          material={materials.Stone_Light}
        />
        <mesh
          name="Wall_SecondAge_2"
          castShadow
          receiveShadow
          geometry={nodes.Wall_SecondAge_2.geometry}
          material={materials.Wood}
        />
      </group>
      <group
        name="Wall"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        userData={{ name: "Wall" }}
      >
        <mesh
          name="Wall_1"
          castShadow
          receiveShadow
          geometry={nodes.Wall_1.geometry}
          material={materials.Highlights}
        />
        <mesh
          name="Wall_2"
          castShadow
          receiveShadow
          geometry={nodes.Wall_2.geometry}
          material={materials.Main}
        />
      </group>
      <mesh
        name="dumpster"
        castShadow
        receiveShadow
        geometry={nodes.dumpster.geometry}
        material={materials["Material.019"]}
        userData={{ name: "dumpster" }}
      />
      <group
        name="box"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        userData={{ name: "box" }}
      >
        <mesh
          name="box_1"
          castShadow
          receiveShadow
          geometry={nodes.box_1.geometry}
          material={materials.DarkBrown}
        />
        <mesh
          name="box_2"
          castShadow
          receiveShadow
          geometry={nodes.box_2.geometry}
          material={materials.Brown}
        />
      </group>
      <mesh
        name="papers"
        castShadow
        receiveShadow
        geometry={nodes.papers.geometry}
        material={materials.White}
        rotation={[-Math.PI / 2, 0, 0.308]}
        scale={11.411}
        userData={{ name: "papers" }}
      />
      <mesh
        name="Group"
        castShadow
        receiveShadow
        geometry={nodes.Group.geometry}
        material={materials["wood.001"]}
        userData={{ name: "Group" }}
      />
      <mesh
        name="stairsOpenSingle"
        castShadow
        receiveShadow
        geometry={nodes.stairsOpenSingle.geometry}
        material={materials.metal}
        userData={{ name: "stairsOpenSingle" }}
      />
      <mesh
        name="Group001"
        castShadow
        receiveShadow
        geometry={nodes.Group001.geometry}
        material={materials["wood.001"]}
        userData={{ name: "Group.001" }}
      />
      <mesh
        name="stairsOpenSingle001"
        castShadow
        receiveShadow
        geometry={nodes.stairsOpenSingle001.geometry}
        material={materials.metal}
        userData={{ name: "stairsOpenSingle.001" }}
      />
      <mesh
        name="invisible-stair"
        castShadow
        receiveShadow
        geometry={nodes["invisible-stair"].geometry}
        material={materials.invisible}
        userData={{ name: "invisible-stair" }}
      />
      <group name="MetalFence" scale={100} userData={{ name: "MetalFence" }}>
        <mesh
          name="MetalFence_1"
          castShadow
          receiveShadow
          geometry={nodes.MetalFence_1.geometry}
          material={materials.Grey}
        />
        <mesh
          name="MetalFence_2"
          castShadow
          receiveShadow
          geometry={nodes.MetalFence_2.geometry}
          material={materials.Texture_Fence}
        />
      </group>
      <group
        name="Debris_Pile"
        scale={58.842}
        userData={{ name: "Debris_Pile" }}
      >
        <mesh
          name="Debris_Pile_1"
          castShadow
          receiveShadow
          geometry={nodes.Debris_Pile_1.geometry}
          material={materials["Wood.001"]}
        />
        <mesh
          name="Debris_Pile_2"
          castShadow
          receiveShadow
          geometry={nodes.Debris_Pile_2.geometry}
          material={materials["Grey.001"]}
        />
        <mesh
          name="Debris_Pile_3"
          castShadow
          receiveShadow
          geometry={nodes.Debris_Pile_3.geometry}
          material={materials.Red}
        />
      </group>
      <group
        name="Barrier_Single"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[73.788, 36.473, 36.473]}
        userData={{ name: "Barrier_Single" }}
      >
        <mesh
          name="Barrier_Single_1"
          castShadow
          receiveShadow
          geometry={nodes.Barrier_Single_1.geometry}
          material={materials["Grey.002"]}
        />
        <mesh
          name="Barrier_Single_2"
          castShadow
          receiveShadow
          geometry={nodes.Barrier_Single_2.geometry}
          material={materials.DarkGrey}
        />
        <mesh
          name="Barrier_Single_3"
          castShadow
          receiveShadow
          geometry={nodes.Barrier_Single_3.geometry}
          material={materials.Yellow}
        />
        <mesh
          name="Barrier_Single_4"
          castShadow
          receiveShadow
          geometry={nodes.Barrier_Single_4.geometry}
          material={materials["White.001"]}
        />
      </group>
      <mesh
        name="invisible-wall"
        castShadow
        receiveShadow
        geometry={nodes["invisible-wall"].geometry}
        material={materials.invisible}
        userData={{ name: "invisible-wall" }}
      />
      <group name="pipe-1" userData={{ name: "pipe-1" }}>
        <mesh
          name="Pipes"
          castShadow
          receiveShadow
          geometry={nodes.Pipes.geometry}
          material={materials.Pipes}
          scale={100}
          userData={{ name: "Pipes" }}
        />
      </group>
      <group name="Pipes001" userData={{ name: "Pipes.001" }}>
        <group
          name="Pipes002"
          rotation={[0, 0, -Math.PI / 2]}
          scale={88.009}
          userData={{ name: "Pipes.002" }}
        >
          <mesh
            name="Pipes001_1"
            castShadow
            receiveShadow
            geometry={nodes.Pipes001_1.geometry}
            material={materials["Grey.003"]}
          />
          <mesh
            name="Pipes001_2"
            castShadow
            receiveShadow
            geometry={nodes.Pipes001_2.geometry}
            material={materials.Grey2}
          />
        </group>
      </group>
      <group
        name="skafold"
        position={[1, 1, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        userData={{ name: "skafold" }}
      >
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          name="Cube005_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_1.geometry}
          material={materials["Material.004"]}
        />
        <mesh
          name="Cube005_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_2.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          name="Cube005_3"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_3.geometry}
          material={materials["Material.007"]}
        />
        <mesh
          name="Cube005_4"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_4.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          name="Cube005_5"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_5.geometry}
          material={materials["Material.009"]}
        />
        <mesh
          name="Cube005_6"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_6.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          name="Cube005_7"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_7.geometry}
          material={materials["Material.011"]}
        />
        <mesh
          name="Cube005_8"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_8.geometry}
          material={materials["Material.025"]}
        />
        <mesh
          name="Cube005_9"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_9.geometry}
          material={materials["Material.026"]}
        />
        <mesh
          name="Cube005_10"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_10.geometry}
          material={materials["Material.027"]}
        />
        <mesh
          name="Cube005_11"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_11.geometry}
          material={materials["Material.028"]}
        />
        <mesh
          name="Cube005_12"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_12.geometry}
          material={materials["Material.029"]}
        />
        <mesh
          name="Cube005_13"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_13.geometry}
          material={materials["Material.030"]}
        />
        <mesh
          name="Cube005_14"
          castShadow
          receiveShadow
          geometry={nodes.Cube005_14.geometry}
          material={materials["Material.031"]}
        />
      </group>
      <mesh
        name="Cable_Long"
        castShadow
        receiveShadow
        geometry={nodes.Cable_Long.geometry}
        material={materials.Black}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        userData={{ name: "Cable_Long" }}
      />
      <group
        name="cyber-Platform_4x1"
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
        userData={{ name: "cyber-Platform_4x1" }}
      >
        <mesh
          name="Platform_4x1"
          castShadow
          receiveShadow
          geometry={nodes.Platform_4x1.geometry}
          material={materials.LightGrey}
        />
        <mesh
          name="Platform_4x1_1"
          castShadow
          receiveShadow
          geometry={nodes.Platform_4x1_1.geometry}
          material={materials["Grey.004"]}
        />
        <mesh
          name="Platform_4x1_2"
          castShadow
          receiveShadow
          geometry={nodes.Platform_4x1_2.geometry}
          material={materials.Texture_Signs}
        />
        <mesh
          name="Platform_4x1_3"
          castShadow
          receiveShadow
          geometry={nodes.Platform_4x1_3.geometry}
          material={materials["Black.001"]}
        />
        <mesh
          name="Platform_4x1_4"
          castShadow
          receiveShadow
          geometry={nodes.Platform_4x1_4.geometry}
          material={materials.Orange}
        />
        <mesh
          name="Platform_4x1_5"
          castShadow
          receiveShadow
          geometry={nodes.Platform_4x1_5.geometry}
          material={materials["DarkGrey.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(MODELS.CITY);

export default BrokenDownCity;

// File is modified to apply the required enhancements
// Converter Made by @NikkitaFTW & contributors inspired by the gltfjsx cli
